// <auto-generated />
using System;
using MagicVilla_API.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVillaAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240330024354_FeedDataMigration")]
    partial class FeedDataMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicVilla_API.Modelos.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MetrosCuadrados")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ocupantes")
                        .HasColumnType("int");

                    b.Property<double>("Tarifa")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenidad = "Piscina",
                            Detalle = "Villa de lujo",
                            FechaActualizacion = new DateTime(2024, 3, 29, 20, 43, 54, 197, DateTimeKind.Local).AddTicks(8887),
                            FechaCreacion = new DateTime(2024, 3, 29, 20, 43, 54, 197, DateTimeKind.Local).AddTicks(8876),
                            ImagenUrl = "",
                            MetrosCuadrados = 200,
                            Nombre = "Villa Real",
                            Ocupantes = 6,
                            Tarifa = 1000.0
                        },
                        new
                        {
                            Id = 2,
                            Amenidad = "",
                            Detalle = "Villa en otro lado",
                            FechaActualizacion = new DateTime(2024, 3, 29, 20, 43, 54, 197, DateTimeKind.Local).AddTicks(8893),
                            FechaCreacion = new DateTime(2024, 3, 29, 20, 43, 54, 197, DateTimeKind.Local).AddTicks(8892),
                            ImagenUrl = "",
                            MetrosCuadrados = 30,
                            Nombre = "Villa Diferente",
                            Ocupantes = 2,
                            Tarifa = 100.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
